export const OFFICE_THEME = {
  shell: {
    bg: '#070b13',
    panel: '#111827',
    panelAlt: '#171f30',
    line: '#2d3b57',
    lineSoft: '#40506b',
    text: '#edf4ff',
    textMuted: '#9caecb',
    accent: '#78a5ff',
    accentSoft: '#1f3f78',
    success: '#62c789',
    warning: '#f8b84e',
    danger: '#ea6d7e',
  },
  world: {
    void: 0x05070b,
    shadow: 0x000000,
    selection: 0x78a5ff,
    interaction: 0xf8b84e,
    signage: 0xdbeafe,
    signageMuted: 0x94a3b8,
    brandingWall: 0x142033,
    brandingTrim: 0x273b5d,
    backdrop: 0xf4f1ea,
    wallBase: 0xf5f1e8,
    wallTrimLight: 0xcfc7b8,
    wallLine: 0x3d3737,
  },
  assets: {
    floors: {
      work: '/assets/pixel-agents/floors/floor_0.png',
      meeting: '/assets/pixel-agents/floors/floor_7.png',
      lounge: '/assets/pixel-agents/floors/floor_1.png',
    },
    walls: {
      office: '/assets/pixel-agents/walls/wall_0.png',
    },
    characters: [
      '/assets/pixel-agents/characters/char_0.png',
      '/assets/pixel-agents/characters/char_1.png',
      '/assets/pixel-agents/characters/char_2.png',
      '/assets/pixel-agents/characters/char_3.png',
      '/assets/pixel-agents/characters/char_4.png',
      '/assets/pixel-agents/characters/char_5.png',
    ],
    furniture: {
      deskFront: '/assets/pixel-agents/furniture/DESK/DESK_FRONT.png',
      deskSide: '/assets/pixel-agents/furniture/DESK/DESK_SIDE.png',
      pcOn: [
        '/assets/pixel-agents/furniture/PC/PC_FRONT_ON_1.png',
        '/assets/pixel-agents/furniture/PC/PC_FRONT_ON_2.png',
        '/assets/pixel-agents/furniture/PC/PC_FRONT_ON_3.png',
      ],
      pcOff: '/assets/pixel-agents/furniture/PC/PC_FRONT_OFF.png',
      pcSide: '/assets/pixel-agents/furniture/PC/PC_SIDE.png',
      pcBack: '/assets/pixel-agents/furniture/PC/PC_BACK.png',
      chairFront: '/assets/pixel-agents/furniture/WOODEN_CHAIR/WOODEN_CHAIR_FRONT.png',
      chairSide: '/assets/pixel-agents/furniture/WOODEN_CHAIR/WOODEN_CHAIR_SIDE.png',
      chairBack: '/assets/pixel-agents/furniture/WOODEN_CHAIR/WOODEN_CHAIR_BACK.png',
      whiteboard: '/assets/pixel-agents/furniture/WHITEBOARD/WHITEBOARD.png',
      coffee: '/assets/pixel-agents/furniture/COFFEE/COFFEE.png',
      sofaFront: '/assets/pixel-agents/furniture/SOFA/SOFA_FRONT.png',
      sofaSide: '/assets/pixel-agents/furniture/SOFA/SOFA_SIDE.png',
      plant: '/assets/pixel-agents/furniture/PLANT/PLANT.png',
      largePlant: '/assets/pixel-agents/furniture/LARGE_PLANT/LARGE_PLANT.png',
      bookshelf: '/assets/pixel-agents/furniture/BOOKSHELF/BOOKSHELF.png',
      doubleBookshelf: '/assets/pixel-agents/furniture/DOUBLE_BOOKSHELF/DOUBLE_BOOKSHELF.png',
      smallTableFront: '/assets/pixel-agents/furniture/SMALL_TABLE/SMALL_TABLE_FRONT.png',
      coffeeTable: '/assets/pixel-agents/furniture/COFFEE_TABLE/COFFEE_TABLE.png',
      clock: '/assets/pixel-agents/furniture/CLOCK/CLOCK.png',
      bin: '/assets/pixel-agents/furniture/BIN/BIN.png',
      smallPainting: '/assets/pixel-agents/furniture/SMALL_PAINTING/SMALL_PAINTING.png',
      largePainting: '/assets/pixel-agents/furniture/LARGE_PAINTING/LARGE_PAINTING.png',
      hangingPlant: '/assets/pixel-agents/furniture/HANGING_PLANT/HANGING_PLANT.png',
    },
  },
  status: {
    typing: { icon: 'typing', label: '집중 작업 중' },
    thinking: { icon: 'think', label: '전략 구상 중' },
    idle: { icon: 'idle', label: '대기 중' },
    meeting: { icon: 'meet', label: '회의 집중 모드' },
    break: { icon: 'break', label: '휴식 중' },
  },
} as const
